export interface IChapterTimeline {
  year: number;
  chapters: string[];
}

export const chapterTimeline: IChapterTimeline[] = [
  { year: 1948, chapters: ["hunt"] },
  { year: 1952, chapters: ["health", "contraband"] },
  { year: 1955, chapters: ["sport", "contraband", "hunt"] },
  { year: 1957, chapters: ["bridge"] },
  { year: 1961, chapters: ["tourism"] },
  { year: 1962, chapters: ["alpeadria"] },
  { year: 1963, chapters: ["tourism"] },
  { year: 1965, chapters: ["politics", "mount"] },
  { year: 1969, chapters: ["politics", "business"] },
  { year: 1971, chapters: ["tvkc"] },
  { year: 1972, chapters: ["tourism", "contraband"] },

  { year: 1976, chapters: ["sport"] },
  { year: 1977, chapters: ["sport"] },
  { year: 1978, chapters: ["sport"] },
  { year: 1979, chapters: ["sport"] },
  { year: 1980, chapters: ["sport"] },
  { year: 1981, chapters: ["sport"] },
  { year: 1982, chapters: ["sport"] },
  { year: 1983, chapters: ["sport"] },
  { year: 1984, chapters: ["sport"] },
  { year: 1985, chapters: ["sport"] },
  { year: 1986, chapters: ["sport"] },
  { year: 1987, chapters: ["sport"] },
  { year: 1988, chapters: ["sport"] },
  { year: 1989, chapters: ["sport"] },
  { year: 1990, chapters: ["sport"] },
  { year: 1991, chapters: ["sport"] },
  { year: 1992, chapters: ["sport"] },

  { year: 1978, chapters: ["alpeadria", "sport"] },
  { year: 1979, chapters: ["sport"] },
  { year: 1980, chapters: ["sport"] },
  { year: 1981, chapters: ["sport"] },
  { year: 1982, chapters: ["sport"] },
  { year: 1983, chapters: ["sport"] },
  { year: 1984, chapters: ["sport"] },
  { year: 1985, chapters: ["sport"] },
  { year: 1986, chapters: ["sport"] },
  { year: 1987, chapters: ["sport"] },
  { year: 1988, chapters: ["sport"] },
  { year: 1989, chapters: ["sport"] },
  { year: 1990, chapters: ["sport"] },
  { year: 1991, chapters: ["sport"] },
  { year: 1992, chapters: ["sport"] },
  { year: 1993, chapters: ["sport"] },
  { year: 1994, chapters: ["sport"] },

  { year: 1980, chapters: ["mount"] },
  { year: 1988, chapters: ["punk"] },
  { year: 1991, chapters: ["politics"] },
  { year: 2015, chapters: ["bridge"] },
  { year: 2023, chapters: ["bridge"] },
];
